server.port=8082
spring.application.name=product-service

spring.data.mongodb.uri=mongodb://localhost:27017/heritcraft_db
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Razorpay Test Mode Configurations
razorpay.key.id=rzp_test_SyFJyf7e3KePe1
razorpay.key.secret=jfEuiZK24pQunxH33rp7JWrZ
