server.port=8081
spring.application.name=user-service

# Oracle DB Configuration
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=heritcraft
spring.datasource.password=root
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# Logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Performance
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# JWT Configuration
jwt.secret=HeritCraftSecretKey2026SuperSecureJWTSigningKeyForTokenAuth!@#456
jwt.expiration=86400000

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ahi06ruki@gmail.com
spring.mail.password=qxdk nepz grch buzn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# RSA Encryption Keys
rsa.private.key=MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC+shEje5byU1Ree1M9qXJ/dAxPMIbM30vb91JfdYhDJyXN3tRwqNfhMhMt47eg+0umgf396x+olpoQdD5duZVnr8evFwiADB818xRNmOrdJZF/EXM001RANDwmQ5k9EzU+Rev5kecebGS/nkfUUWJ8e4vQuZBMreyUqBAYIps6WFRBPpzY4jz7fXuz2wkdnDVHJWuDFb4qZsfCkZnQj2ya90EUTQXnPkzgLy2GlR48ejlnoejCAMKcb8JNoEfTT12OueXi6FlfUqHCWLI4BUjDU8DhA5tF9gXxBK1PbBTi09ieelT0wlSK5Fwsp0CvX0qZfuXzOho2a80PUV1YDuSlAgMBAAECggEAUBN2HvBG8nsLcqFW0w3UhrC0eoxmDqG1uSih7nPsREasGUb47lX4URg19Y8qDO95VPJBNd8F7EVRbJdjmPfVRTULJPsHFr4AXSc131/XQAYGktVBC22yc0N7/pVkQ8FNGllCPgqGgsABjnVotD94m81FaOCDN6/RKJtqJrhhdp3mkbz6SzLkyGLdW7+2FbNvN8H/PFjGVP0VoFx/wjb8iI0ZJvRmyVmzZBW331AphQyu9/+E00cCSlFzJiDddgdVeuTEF1zxwb/ZmN1KHDmC+uWc+vbtkJSVuVmkLvH32Fw3YsYArbgQnXrRDjqNgy0APL2Vj6R6Lf0wfrxtoS3aAQKBgQDv9ZI+Ubu/mEiaiW88RfHRwrauFreUVa+qpH+lxU1K1vgGc6CMjXCySXiqODYgiVozi0EhV4AYIOiwftKmtO1+H52dJD7pixYJHRiptEL5RHrkZwFsv/CFzCutaZZEsNEIzZkwQNWHtc2rUGjvmDtkx6/ZQZolTnznde9R+cLOdwKBgQDLcXHpw3ShJwFUFLfWw6ICEtvFxgrKJj8NXU5hTW2aoC+77fFoG0l3e9Zm1NhcKbDN2sFBSaX46Er2gAfwrrW1vSea8F0luGOiiVp/pRCbNm6qwnS1AKSynnQcZQinBSxW+DJgWhhGrbB0DPQ8RjlMbTcQvP3uL3SRGPcQc3lgwwKBgEdhLnKZT5crzpUhwtQUHl3+ZOceXNekMZA6RLpkGZzkm30X0i9dN6PhVSKVfAxrr0hb6TDo3XLP/0fZQgJTGb6F2xXOnWRNem2VmSuKMs4Bf+kHdxYJdpvmYyu/l/KxAk1zE1mWP66R9y85yS1UhH5zJC0lZZwpX+BeZaVl/Xv7AoGBAKPIg/W3Jjjq5vXi7BHZU58pwYbaJiuSWOaQfJ53MErwtR0ttVCjzySDLRuCNWEVK0K+3yCJgzX9BQSoFDxe2ukiDDV/Vu4cIRJkU9g5ckISs0uD22MwzmcCi+WkLTARSR4HGL9bKPoVsN3s4992hYCS2GcAT8omqEh7+cNjw47zAoGBAMW7UnFPX47aJPvxHfGS+ABrv9KqdtomnF0dPeTuaZlLjBn5y0AQI9aRKErAPBJrzzHus4ONAPiRlxUMlvPeHK2jjJ5O8L2WlsWIiBaI8nMP77qXJ04aFVtzHXx6ZN6kFUkZkKDWyx+ZKL+k/Sii8hh/SPYUysmf9+6uPGmLEpLt
rsa.public.key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvrIRI3uW8lNUXntTPalyf3QMTzCGzN9L2/dSX3WIQyclzd7UcKjX4TITLeO3oPtLpoH9/esfqJaaEHQ+XbmVZ6/HrxcIgAwfNfMUTZjq3SWRfxFzNNNUQDQ8JkOZPRM1PkXr+ZHnHmxkv55H1FFifHuL0LmQTK3slKgQGCKbOlhUQT6c2OI8+317s9sJHZw1RyVrgxW+KmbHwpGZ0I9smvdBFE0F5z5M4C8thpUePHo5Z6HowgDCnG/CTaBH009djrnl4uhZX1KhwliyOAVIw1PA4QObRfYF8QStT2wU4tPYnnpU9MJUiuRcLKdAr19KmX7l8zoaNmvND1FdWA7kpQIDAQAB

